name: greeklish
description: Greeklish Generator
version: 0.0.1
author: George Chailazopoulos
homepage: https://github.com/spiritinlife/greeklish_dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
